title: "William J. Owens' Portfolio"
description: "Data Professional showcasing projects and skills."
baseurl: "" # Leave empty unless deploying to a subpath
url: "https://williamjowens.github.io" # GitHub Pages URL
theme: minima
plugins:
  - jekyll-seo-tag

# Define collections (if any)
collections:
  # No collections needed since projects are on the homepage

# Navigation Links
navigation:
  - title: "Home"
    url: "/"