title: "William J. Owens"
description: "Data Professional showcasing projects and skills."
baseurl: "" # Leave empty unless deploying to a subpath
url: "https://williamjowens.github.io" # GitHub Pages URL

# Dinky theme
theme: jekyll-theme-dinky

plugins:
  - jekyll-seo-tag

# Navigation Links
navigation:
  - title: "Home"
    url: "/"